[package]
name = "nnlm"
version = "0.1.0"
edition = "2024"

[dependencies]
stmc_rs = { git = "https://github.com/jesper-olsen/stmc-rs", branch = "master" }
nalgebra = "0.33.2"
gnuplot = "0.0.46"
clap = { version = "4.5.37", features = ["derive"] }
log = "0.4.27"
env_logger = "0.11.8"

